# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11MessageType.proto\x12\x08protobuf*g\n\tPlaceType\x12\x13\n\x0fNULL_PLACE_TYPE\x10\x00\x12\x08\n\x04LAND\x10\x01\x12\x08\n\x04WALL\x10\x02\x12\t\n\x05GRASS\x10\x03\x12\x0b\n\x07MACHINE\x10\x04\x12\x08\n\x04GATE\x10\x05\x12\x0f\n\x0bHIDDEN_GATE\x10\x06*8\n\tShapeType\x12\x13\n\x0fNULL_SHAPE_TYPE\x10\x00\x12\n\n\x06\x43IRCLE\x10\x01\x12\n\n\x06SQUARE\x10\x02*N\n\x08PropType\x12\x12\n\x0eNULL_PROP_TYPE\x10\x00\x12\n\n\x06PTYPE1\x10\x01\x12\n\n\x06PTYPE2\x10\x02\x12\n\n\x06PTYPE3\x10\x03\x12\n\n\x06PTYPE4\x10\x04*d\n\rHumanBuffType\x12\x13\n\x0fNULL_HBUFF_TYPE\x10\x00\x12\x0e\n\nHBUFFTYPE1\x10\x01\x12\x0e\n\nHBUFFTYPE2\x10\x02\x12\x0e\n\nHBUFFTYPE3\x10\x03\x12\x0e\n\nHBUFFTYPE4\x10\x04*V\n\nHumanState\x12\x0f\n\x0bNULL_STATUS\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\n\n\x06\x46IXING\x10\x02\x12\t\n\x05\x44YING\x10\x03\x12\x0c\n\x08ON_CHAIR\x10\x04\x12\x08\n\x04\x44\x45\x41\x44\x10\x05*f\n\x0f\x42utcherBuffType\x12\x13\n\x0fNULL_BBUFF_TYPE\x10\x00\x12\x0e\n\nBBUFFTYPE1\x10\x01\x12\x0e\n\nBBUFFTYPE2\x10\x02\x12\x0e\n\nBBUFFTYPE3\x10\x03\x12\x0e\n\nBBUFFTYPE4\x10\x04*H\n\nPlayerType\x12\x14\n\x10NULL_PLAYER_TYPE\x10\x00\x12\x10\n\x0cHUMAN_PLAYER\x10\x01\x12\x12\n\x0e\x42UTCHER_PLAYER\x10\x02*`\n\tHumanType\x12\x13\n\x0fNULL_HUMAN_TYPE\x10\x00\x12\x0e\n\nHUMANTYPE1\x10\x01\x12\x0e\n\nHUMANTYPE2\x10\x02\x12\x0e\n\nHUMANTYPE3\x10\x03\x12\x0e\n\nHUMANTYPE4\x10\x04*l\n\x0b\x42utcherType\x12\x15\n\x11NULL_BUTCHER_TYPE\x10\x00\x12\x10\n\x0c\x42UTCHERTYPE1\x10\x01\x12\x10\n\x0c\x42UTCHERTYPE2\x10\x02\x12\x10\n\x0c\x42UTCHERTYPE3\x10\x03\x12\x10\n\x0c\x42UTCHERTYPE4\x10\x04*P\n\tGameState\x12\x13\n\x0fNULL_GAME_STATE\x10\x00\x12\x0e\n\nGAME_START\x10\x01\x12\x10\n\x0cGAME_RUNNING\x10\x02\x12\x0c\n\x08GAME_END\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'MessageType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _PLACETYPE._serialized_start = 31
    _PLACETYPE._serialized_end = 134
    _SHAPETYPE._serialized_start = 136
    _SHAPETYPE._serialized_end = 192
    _PROPTYPE._serialized_start = 194
    _PROPTYPE._serialized_end = 272
    _HUMANBUFFTYPE._serialized_start = 274
    _HUMANBUFFTYPE._serialized_end = 374
    _HUMANSTATE._serialized_start = 376
    _HUMANSTATE._serialized_end = 462
    _BUTCHERBUFFTYPE._serialized_start = 464
    _BUTCHERBUFFTYPE._serialized_end = 566
    _PLAYERTYPE._serialized_start = 568
    _PLAYERTYPE._serialized_end = 640
    _HUMANTYPE._serialized_start = 642
    _HUMANTYPE._serialized_end = 738
    _BUTCHERTYPE._serialized_start = 740
    _BUTCHERTYPE._serialized_end = 848
    _GAMESTATE._serialized_start = 850
    _GAMESTATE._serialized_end = 930
# @@protoc_insertion_point(module_scope)
