// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from MessageType.proto</summary>
  public static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for MessageType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNZXNzYWdlVHlwZS5wcm90bxIIcHJvdG9idWYqhwEKCkJ1bGxldFR5cGUS",
            "FAoQTlVMTF9CVUxMRVRfVFlQRRAAEhAKDEZMWUlOR19LTklGRRABEhwKGENP",
            "TU1PTl9BVFRBQ0tfT0ZfVFJJQ0tFUhACEg8KC0ZBU1RfQlVMTEVUEAMSEwoP",
            "T1JESU5BUllfQlVMTEVUEAQSDQoJQVRPTV9CT01CEAUqoQEKCVBsYWNlVHlw",
            "ZRITCg9OVUxMX1BMQUNFX1RZUEUQABIICgRMQU5EEAESCAoEV0FMTBACEgkK",
            "BUdSQVNTEAMSDQoJQ0xBU1NST09NEAQSCAoER0FURRAFEg8KC0hJRERFTl9H",
            "QVRFEAYSCgoGV0lORE9XEAcSCQoFRE9PUjMQCBIJCgVET09SNRAJEgkKBURP",
            "T1I2EAoSCQoFQ0hFU1QQCyo4CglTaGFwZVR5cGUSEwoPTlVMTF9TSEFQRV9U",
            "WVBFEAASCgoGQ0lSQ0xFEAESCgoGU1FVQVJFEAIqSAoIUHJvcFR5cGUSEgoO",
            "TlVMTF9QUk9QX1RZUEUQABIICgRLRVkzEAESCAoES0VZNRACEggKBEtFWTYQ",
            "AxIKCgZQVFlQRTQQBCpmCg9TdHVkZW50QnVmZlR5cGUSEwoPTlVMTF9TQlVG",
            "Rl9UWVBFEAASDgoKU0JVRkZUWVBFMRABEg4KClNCVUZGVFlQRTIQAhIOCgpT",
            "QlVGRlRZUEUzEAMSDgoKU0JVRkZUWVBFNBAEKqkCCgtQbGF5ZXJTdGF0ZRIP",
            "CgtOVUxMX1NUQVRVUxAAEggKBElETEUQARIMCghMRUFSTklORxACEgwKCEFE",
            "RElDVEVEEAMSCAoEUVVJVBAEEg0KCUdSQURVQVRFRBAFEgsKB1RSRUFURUQQ",
            "BhILCgdSRVNDVUVEEAcSCwoHU1RVTk5FRBAIEgwKCFRSRUFUSU5HEAkSDAoI",
            "UkVTQ1VJTkcQChIMCghTV0lOR0lORxALEg0KCUFUVEFDS0lORxAMEgsKB0xP",
            "Q0tJTkcQDRINCglSVU1NQUdJTkcQDhIMCghDTElNQklORxAPEhMKD09QRU5J",
            "TkdfQV9DSEVTVBAQEhcKE1VTSU5HX1NQRUNJQUxfU0tJTEwQERISCg5PUEVO",
            "SU5HX0FfR0FURRASKmYKD1RyaWNrZXJCdWZmVHlwZRITCg9OVUxMX1RCVUZG",
            "X1RZUEUQABIOCgpUQlVGRlRZUEUxEAESDgoKVEJVRkZUWVBFMhACEg4KClRC",
            "VUZGVFlQRTMQAxIOCgpUQlVGRlRZUEU0EAQqSgoKUGxheWVyVHlwZRIUChBO",
            "VUxMX1BMQVlFUl9UWVBFEAASEgoOU1RVREVOVF9QTEFZRVIQARISCg5UUklD",
            "S0VSX1BMQVlFUhACKmcKC1N0dWRlbnRUeXBlEhUKEU5VTExfU1RVREVOVF9U",
            "WVBFEAASCwoHQVRITEVURRABEhAKDFNUVURFTlRUWVBFMhACEhAKDFNUVURF",
            "TlRUWVBFMxADEhAKDFNUVURFTlRUWVBFNBAEKmgKC1RyaWNrZXJUeXBlEhUK",
            "EU5VTExfVFJJQ0tFUl9UWVBFEAASDAoIQVNTQVNTSU4QARIQCgxUUklDS0VS",
            "VFlQRTIQAhIQCgxUUklDS0VSVFlQRTMQAxIQCgxUUklDS0VSVFlQRTQQBCpQ",
            "CglHYW1lU3RhdGUSEwoPTlVMTF9HQU1FX1NUQVRFEAASDgoKR0FNRV9TVEFS",
            "VBABEhAKDEdBTUVfUlVOTklORxACEgwKCEdBTUVfRU5EEANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protobuf.BulletType), typeof(global::Protobuf.PlaceType), typeof(global::Protobuf.ShapeType), typeof(global::Protobuf.PropType), typeof(global::Protobuf.StudentBuffType), typeof(global::Protobuf.PlayerState), typeof(global::Protobuf.TrickerBuffType), typeof(global::Protobuf.PlayerType), typeof(global::Protobuf.StudentType), typeof(global::Protobuf.TrickerType), typeof(global::Protobuf.GameState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum BulletType {
    [pbr::OriginalName("NULL_BULLET_TYPE")] NullBulletType = 0,
    [pbr::OriginalName("FLYING_KNIFE")] FlyingKnife = 1,
    [pbr::OriginalName("COMMON_ATTACK_OF_TRICKER")] CommonAttackOfTricker = 2,
    [pbr::OriginalName("FAST_BULLET")] FastBullet = 3,
    [pbr::OriginalName("ORDINARY_BULLET")] OrdinaryBullet = 4,
    [pbr::OriginalName("ATOM_BOMB")] AtomBomb = 5,
  }

  public enum PlaceType {
    [pbr::OriginalName("NULL_PLACE_TYPE")] NullPlaceType = 0,
    /// <summary>
    /// 地图情况，其中Gate是总体的大门，HiddenGate是地窖
    /// </summary>
    [pbr::OriginalName("LAND")] Land = 1,
    [pbr::OriginalName("WALL")] Wall = 2,
    [pbr::OriginalName("GRASS")] Grass = 3,
    [pbr::OriginalName("CLASSROOM")] Classroom = 4,
    [pbr::OriginalName("GATE")] Gate = 5,
    [pbr::OriginalName("HIDDEN_GATE")] HiddenGate = 6,
    [pbr::OriginalName("WINDOW")] Window = 7,
    [pbr::OriginalName("DOOR3")] Door3 = 8,
    [pbr::OriginalName("DOOR5")] Door5 = 9,
    [pbr::OriginalName("DOOR6")] Door6 = 10,
    /// <summary>
    /// 待补充有特殊效果的地形
    /// </summary>
    [pbr::OriginalName("CHEST")] Chest = 11,
  }

  public enum ShapeType {
    [pbr::OriginalName("NULL_SHAPE_TYPE")] NullShapeType = 0,
    /// <summary>
    /// 人类、屠夫、可拾取道具等为圆形
    /// </summary>
    [pbr::OriginalName("CIRCLE")] Circle = 1,
    /// <summary>
    /// 地形均为方形
    /// </summary>
    [pbr::OriginalName("SQUARE")] Square = 2,
  }

  public enum PropType {
    [pbr::OriginalName("NULL_PROP_TYPE")] NullPropType = 0,
    [pbr::OriginalName("KEY3")] Key3 = 1,
    [pbr::OriginalName("KEY5")] Key5 = 2,
    [pbr::OriginalName("KEY6")] Key6 = 3,
    [pbr::OriginalName("PTYPE4")] Ptype4 = 4,
  }

  public enum StudentBuffType {
    [pbr::OriginalName("NULL_SBUFF_TYPE")] NullSbuffType = 0,
    [pbr::OriginalName("SBUFFTYPE1")] Sbufftype1 = 1,
    [pbr::OriginalName("SBUFFTYPE2")] Sbufftype2 = 2,
    [pbr::OriginalName("SBUFFTYPE3")] Sbufftype3 = 3,
    [pbr::OriginalName("SBUFFTYPE4")] Sbufftype4 = 4,
  }

  public enum PlayerState {
    [pbr::OriginalName("NULL_STATUS")] NullStatus = 0,
    /// <summary>
    /// 正常状态
    /// </summary>
    [pbr::OriginalName("IDLE")] Idle = 1,
    /// <summary>
    /// 学习状态，相当于在修机器
    /// </summary>
    [pbr::OriginalName("LEARNING")] Learning = 2,
    /// <summary>
    /// 血条归零后原地沉迷游戏
    /// </summary>
    [pbr::OriginalName("ADDICTED")] Addicted = 3,
    /// <summary>
    /// 退学状态，相当于寄了
    /// </summary>
    [pbr::OriginalName("QUIT")] Quit = 4,
    /// <summary>
    /// 毕业状态，相当于逃脱了
    /// </summary>
    [pbr::OriginalName("GRADUATED")] Graduated = 5,
    [pbr::OriginalName("TREATED")] Treated = 6,
    [pbr::OriginalName("RESCUED")] Rescued = 7,
    [pbr::OriginalName("STUNNED")] Stunned = 8,
    [pbr::OriginalName("TREATING")] Treating = 9,
    [pbr::OriginalName("RESCUING")] Rescuing = 10,
    /// <summary>
    /// 后摇
    /// </summary>
    [pbr::OriginalName("SWINGING")] Swinging = 11,
    /// <summary>
    /// 前摇
    /// </summary>
    [pbr::OriginalName("ATTACKING")] Attacking = 12,
    [pbr::OriginalName("LOCKING")] Locking = 13,
    [pbr::OriginalName("RUMMAGING")] Rummaging = 14,
    /// <summary>
    /// 翻窗
    /// </summary>
    [pbr::OriginalName("CLIMBING")] Climbing = 15,
    [pbr::OriginalName("OPENING_A_CHEST")] OpeningAChest = 16,
    [pbr::OriginalName("USING_SPECIAL_SKILL")] UsingSpecialSkill = 17,
    [pbr::OriginalName("OPENING_A_GATE")] OpeningAGate = 18,
  }

  public enum TrickerBuffType {
    [pbr::OriginalName("NULL_TBUFF_TYPE")] NullTbuffType = 0,
    [pbr::OriginalName("TBUFFTYPE1")] Tbufftype1 = 1,
    [pbr::OriginalName("TBUFFTYPE2")] Tbufftype2 = 2,
    [pbr::OriginalName("TBUFFTYPE3")] Tbufftype3 = 3,
    [pbr::OriginalName("TBUFFTYPE4")] Tbufftype4 = 4,
  }

  public enum PlayerType {
    [pbr::OriginalName("NULL_PLAYER_TYPE")] NullPlayerType = 0,
    [pbr::OriginalName("STUDENT_PLAYER")] StudentPlayer = 1,
    [pbr::OriginalName("TRICKER_PLAYER")] TrickerPlayer = 2,
  }

  public enum StudentType {
    [pbr::OriginalName("NULL_STUDENT_TYPE")] NullStudentType = 0,
    [pbr::OriginalName("ATHLETE")] Athlete = 1,
    [pbr::OriginalName("STUDENTTYPE2")] _2 = 2,
    [pbr::OriginalName("STUDENTTYPE3")] _3 = 3,
    [pbr::OriginalName("STUDENTTYPE4")] _4 = 4,
  }

  public enum TrickerType {
    [pbr::OriginalName("NULL_TRICKER_TYPE")] NullTrickerType = 0,
    [pbr::OriginalName("ASSASSIN")] Assassin = 1,
    [pbr::OriginalName("TRICKERTYPE2")] _2 = 2,
    [pbr::OriginalName("TRICKERTYPE3")] _3 = 3,
    [pbr::OriginalName("TRICKERTYPE4")] _4 = 4,
  }

  /// <summary>
  /// 游戏进行状态
  /// </summary>
  public enum GameState {
    [pbr::OriginalName("NULL_GAME_STATE")] NullGameState = 0,
    [pbr::OriginalName("GAME_START")] GameStart = 1,
    [pbr::OriginalName("GAME_RUNNING")] GameRunning = 2,
    [pbr::OriginalName("GAME_END")] GameEnd = 3,
  }

  #endregion

}

#endregion Designer generated code
