// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from Services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for Services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5TZXJ2aWNlcy5wcm90bxIIcHJvdG9idWYaFU1lc3NhZ2UyQ2xpZW50cy5w",
            "cm90bxoUTWVzc2FnZTJTZXJ2ZXIucHJvdG8y6AcKEEF2YWlsYWJsZVNlcnZp",
            "Y2USMwoNVHJ5Q29ubmVjdGlvbhIPLnByb3RvYnVmLklETXNnGhEucHJvdG9i",
            "dWYuQm9vbFJlcxI9CglBZGRQbGF5ZXISEy5wcm90b2J1Zi5QbGF5ZXJNc2ca",
            "GS5wcm90b2J1Zi5NZXNzYWdlVG9DbGllbnQwARIsCgRNb3ZlEhEucHJvdG9i",
            "dWYuTW92ZU1zZxoRLnByb3RvYnVmLk1vdmVSZXMSMAoIUGlja1Byb3ASES5w",
            "cm90b2J1Zi5Qcm9wTXNnGhEucHJvdG9idWYuQm9vbFJlcxIvCgdVc2VQcm9w",
            "EhEucHJvdG9idWYuUHJvcE1zZxoRLnByb3RvYnVmLkJvb2xSZXMSMQoJVGhy",
            "b3dQcm9wEhEucHJvdG9idWYuUHJvcE1zZxoRLnByb3RvYnVmLkJvb2xSZXMS",
            "MQoIVXNlU2tpbGwSEi5wcm90b2J1Zi5Ta2lsbE1zZxoRLnByb3RvYnVmLkJv",
            "b2xSZXMSMwoLU2VuZE1lc3NhZ2USES5wcm90b2J1Zi5TZW5kTXNnGhEucHJv",
            "dG9idWYuQm9vbFJlcxIzCg1TdGFydExlYXJuaW5nEg8ucHJvdG9idWYuSURN",
            "c2caES5wcm90b2J1Zi5Cb29sUmVzEjUKD1N0YXJ0UmVzY3VlTWF0ZRIPLnBy",
            "b3RvYnVmLklETXNnGhEucHJvdG9idWYuQm9vbFJlcxI0Cg5TdGFydFRyZWF0",
            "TWF0ZRIPLnByb3RvYnVmLklETXNnGhEucHJvdG9idWYuQm9vbFJlcxIwCgZB",
            "dHRhY2sSEy5wcm90b2J1Zi5BdHRhY2tNc2caES5wcm90b2J1Zi5Cb29sUmVz",
            "Ei4KCEdyYWR1YXRlEg8ucHJvdG9idWYuSURNc2caES5wcm90b2J1Zi5Cb29s",
            "UmVzEi4KCE9wZW5Eb29yEg8ucHJvdG9idWYuSURNc2caES5wcm90b2J1Zi5C",
            "b29sUmVzEi8KCUNsb3NlRG9vchIPLnByb3RvYnVmLklETXNnGhEucHJvdG9i",
            "dWYuQm9vbFJlcxIwCgpTa2lwV2luZG93Eg8ucHJvdG9idWYuSURNc2caES5w",
            "cm90b2J1Zi5Cb29sUmVzEjMKDVN0YXJ0T3BlbkdhdGUSDy5wcm90b2J1Zi5J",
            "RE1zZxoRLnByb3RvYnVmLkJvb2xSZXMSNAoOU3RhcnRPcGVuQ2hlc3QSDy5w",
            "cm90b2J1Zi5JRE1zZxoRLnByb3RvYnVmLkJvb2xSZXMSMgoMRW5kQWxsQWN0",
            "aW9uEg8ucHJvdG9idWYuSURNc2caES5wcm90b2J1Zi5Cb29sUmVzYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protobuf.Message2ClientsReflection.Descriptor, global::Protobuf.Message2ServerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
