#FROM ubuntu:18.04
FROM eesast/thuai6_base:base
MAINTAINER eesast
WORKDIR /usr/local

COPY ./CAPI/cpp /usr/local/PlayerCode/CAPI/cpp
COPY ./dependency/proto /usr/local/PlayerCode/dependency/proto
COPY ./dependency/shell /usr/local/PlayerCode/dependency/shell
WORKDIR /usr/local/PlayerCode/dependency/proto
RUN bash ../shell/cpp_output.sh
WORKDIR /usr/local/PlayerCode/CAPI/cpp
COPY ./dependency/shell/compile.sh .
ENTRYPOINT ["bash","./compile.sh"]
#WORKDIR /usr/local/PlayerCode/CAPI/cpp
#RUN cmake ./CMakeLists.txt
#RUN make
