#FROM ubuntu:18.04
FROM wangsk21/thuai6:base
MAINTAINER eesast.com
WORKDIR /usr/local

COPY ./CAPI/cpp /usr/local/PlayerCode/CAPI/cpp
COPY ./dependency/proto /usr/local/PlayerCode/dependency/proto
WORKDIR /usr/local/PlayerCode/dependency/proto
RUN ./cpp_output.sh
WORKDIR /usr/local/PlayerCode/CAPI/cpp
COPY ./dependency/shell/compile.sh .
COPY ./dependency/shell/docker.sh /usr/local/
WORKDIR /usr/local
ENTRYPOINT ["bash","./docker.sh"]
#WORKDIR /usr/local/PlayerCode/CAPI/cpp
#RUN cmake ./CMakeLists.txt
#RUN make
