FROM mcr.microsoft.com/dotnet/sdk:6.0.421-jammy-amd64 AS build
MAINTAINER eesast
WORKDIR /usr/local
COPY . .
RUN dotnet publish logic/Server/Server.csproj -c Release -o /usr/local/Server --self-contained true -r linux-x64

FROM eesast/thuai6_base:base
MAINTAINER eesast
WORKDIR /usr/local
COPY --from=build /usr/local/Server .
RUN mkdir /usr/local/team1 && mkdir /usr/local/team2 && mkdir /usr/local/playback
COPY ./dependency/shell/run.sh .
COPY ./CAPI/python /usr/local/PlayerCode/CAPI/python
COPY ./dependency/proto /usr/local/PlayerCode/dependency/proto
COPY ./dependency/shell /usr/local/PlayerCode/dependency/shell
WORKDIR /usr/local/PlayerCode/CAPI/python
RUN bash ../../dependency/shell/generate_proto.sh

WORKDIR /usr/local
ENTRYPOINT [ "bash","./run.sh" ]
