FROM python:3.9.16-bullseye
RUN apt-get update
RUN mkdir /usr/local/PlayerCode
COPY ./CAPI/python /usr/local/PlayerCode/CAPI/python
COPY ./dependency/proto /usr/local/PlayerCode/dependency/proto

WORKDIR /usr/local/PlayerCode/CAPI/python
RUN ./generate_proto.sh
RUN apt-get install --no-install-recommends wget unzip
RUN wget -P . https://cloud.tsinghua.edu.cn/f/e48940314a6d4cdb8bd0/?dl=1
RUN mv 'index.html?dl=1' Server.tar.gz
RUN tar -zxvf Server.tar.gz


